[actions]
start='node --zero-fill-buffers src --'
watch='nodemon'
test='mocha --sort --recursive --check-leaks'
test-watch='mocha --watch --sort --recursive --reporter=dot --check-leaks'
lint='eslint src/ test/'

